### ISSUE TITLE
Error if no parameters are passed to function tg_do_request()

### ISSUE THREAD

**Issue by sebastianertz** [waldner/bashegram#2]
I fix it in function ```tg_array_has_key()```

```bash
tg_array_has_key(){
  local key=$2
  local -n _object_arr=$1

  [ -n "$key"] && [[ "${_object_arr[$key]+foobar}" ]]
}
```

**Comment by waldner** [comment]
Thanks. I think the right fix is to do the check in the `tg_do_request()` function, as its argument is mandatory. (I thought the `tg_is_valid_method()` function would take care of that, but apparently it doesn't, as you point out). I'll push the update in a few minutes.

**Comment by sebastianertz** [comment]
This partly fixes the problem. The error is also without parameters for other functions (tg_is_valid_parse_mode, tg_is_valid_chat_action, tg_is_valid_method, tg_is_valid_inline_query_result_type)

**Comment by waldner** [comment]
Sure, but those functions are never meant to be called from user code (unlike `tg_do_request`). If you're calling them from your code you should know what you're doing. Nevertheless, the fix is simple, so I'll probably add it.

**Comment by waldner** [comment]
Ok, after a bit of testing and thought, your original fix was the right one. I've now implemented it. Thanks
